
#ifndef __ETC_H__
#define __ETC_H__


#include <windows.h>


#define ETC_DRIVER_NAME		_T("ETC1:")
#define	ETC_DRIVER_DEVICE	0x8010
#define	ETC_DRIVER_FUNCTION	0x810

#ifndef	METHOD_NEITHER
#define METHOD_NEITHER		3
#endif
#ifndef	FILE_ANY_ACCESS
#define FILE_ANY_ACCESS		0
#endif
#ifndef	CTL_CODE
#define CTL_CODE(DeviceType, Function, Method, Access) (((DeviceType)<<16) | ((Access)<<14) | ((Function)<<2) | (Method))
#endif


#define IOCTL_SET_POWER_WLAN\
	CTL_CODE(ETC_DRIVER_DEVICE, ETC_DRIVER_FUNCTION+0x01, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_GET_POWER_WLAN\
	CTL_CODE(ETC_DRIVER_DEVICE, ETC_DRIVER_FUNCTION+0x02, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_SET_POWER_WCDMA\
	CTL_CODE(ETC_DRIVER_DEVICE, ETC_DRIVER_FUNCTION+0x03, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_GET_POWER_WCDMA\
	CTL_CODE(ETC_DRIVER_DEVICE, ETC_DRIVER_FUNCTION+0x04, METHOD_NEITHER, FILE_ANY_ACCESS)


// +++ Only System Used +++
#define IOCTL_SET_BOARD_UUID\
	CTL_CODE(ETC_DRIVER_DEVICE, ETC_DRIVER_FUNCTION+0xFF, METHOD_NEITHER, FILE_ANY_ACCESS)
// --- Only System Used ---

#endif //__ETC_H__

