
#ifndef _KEYPAD_H_
#define _KEYPAD_H_

typedef enum
{
	KEY_NONE=0x00,

	KEY_0, KEY_3, KEY_T, KEY_L, KEY_A, KEY_N, KEY_KE, KEY_VOLDOWN,
	KEY_9, KEY_2, KEY_Y, KEY_K, KEY_S, KEY_M, KEY_PP, KEY_VOLUP,
	KEY_8, KEY_1, KEY_U, KEY_J, KEY_Z, KEY_DOT, KEY_NP, KEY_RIGHT,
	KEY_7, KEY_Q, KEY_I, KEY_H, KEY_X, KEY_SLASH, KEY_BACK, KEY_UP,
	KEY_6, KEY_W, KEY_P, KEY_G, KEY_C, KEY_ENTER, KEY_MENU, KEY_ENTER2,
	KEY_5, KEY_E, KEY_O, KEY_F, KEY_V, KEY_SYM, KEY_NP2, KEY_DOWN,
	KEY_4, KEY_R, KEY_BACKSPACE, KEY_D, KEY_B, KEY_FONT, KEY_SPACE, KEY_LEFT,
	KEY_FN, KEY_SHIFT, KEY_ALT, KEY_HOME,

	KEY_HOLD=0x80,
} EKEY_DATA;

void InitializeKeypad(void);
EKEY_DATA GetKeypad(void);
BYTE GetKeypad2(void);

#endif  _KEYPAD_H_

