
#ifndef __EBOOK2_TOUCH_H__
#define __EBOOK2_TOUCH_H__


#include <windows.h>


#define TSP_DRIVER_NAME		_T("TSP1:")
#define TSP_EVENT_NAME		_T("EBOOK2_TSP")
#define	TSP_DRIVER_DEVICE	0x8020
#define	TSP_DRIVER_FUNCTION	0x820

#ifndef	METHOD_NEITHER
#define METHOD_NEITHER		3
#endif
#ifndef	FILE_ANY_ACCESS
#define FILE_ANY_ACCESS		0
#endif
#ifndef	CTL_CODE
#define CTL_CODE(DeviceType, Function, Method, Access) (((DeviceType)<<16) | ((Access)<<14) | ((Function)<<2) | (Method))
#endif


#define IOCTL_TSP_SET_ORIENTATION\
	CTL_CODE(TSP_DRIVER_DEVICE, TSP_DRIVER_FUNCTION+0x01, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_TSP_GET_ORIENTATION\
	CTL_CODE(TSP_DRIVER_DEVICE, TSP_DRIVER_FUNCTION+0x02, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_TSP_SET_ENABLE\
	CTL_CODE(TSP_DRIVER_DEVICE, TSP_DRIVER_FUNCTION+0x03, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_TSP_GET_ENABLE\
	CTL_CODE(TSP_DRIVER_DEVICE, TSP_DRIVER_FUNCTION+0x04, METHOD_NEITHER, FILE_ANY_ACCESS)


#endif //__EBOOK2_TOUCH_H__

